version: "2"

linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - contextcheck
    - copyloopvar
    - decorder
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exptostd
    - fatcontext
    - forcetypeassert
    - funcorder
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecksumtype
    - goheader
    - gocritic
    - goconst
    - gosec
    - gosmopolitan
    - goprintffuncname
    - grouper
    - ineffassign
    - importas
    - inamedparam
    - interfacebloat
    - iface
    - intrange
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - musttag
    - nilerr
    - nilnesserr
    - nilnil
    - nlreturn
    - nolintlint
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - recvcheck
    - reassign
    - rowserrcheck
    - sloglint
    - spancheck
    - staticcheck
    - tagalign
    - testableexamples
    - testifylint
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
    - wsl_v5
    - zerologlint

run:
  tests: true
  concurrency: 4
  timeout: 5m
  issues-exit-code: 1
  modules-download-mode: readonly

issues:
  max-issues-per-linter: 0
  uniq-by-line: true
  fix: true

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
